spring:
  jpa:
    generate-dll: true
    show-sql: true
    hibernate:
      ddl-auto: update

datasource:
  default: ${APP_ENV}
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./database"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: jdbc:postgresql://localhost:8080
ebean:
  migration:
    run: true